MySQL:
  Host: 'Host'
  Port: 3306
  Database: 'Database'
  Username: 'Username'
  Password: 'Password'
General:
  Permission: statssystem.stats
  NoPermissionMessage: '%prefix%&cDazu hast du keine Berechtigung.'
  SenderIsConsole: 'Dies kannst du als Konsole nicht.'
  Prefix: '&8[&3StatsSystem&8] &7'