name: StatsSystem
main: de.javaexceptions.statssystem.StatsSystem
author: JavaExceptions
version: 1.0
api-version: 1.13
description: Test Plugin

commands:
  Stats:
    description: Zeige dir deine Spielstatistiken an.